### ISSUE TITLE
New CLI analysis tool

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1136]
We need a new CLI analysis tool (which can also be run via the Python API) to analyze simulations set up via the perses CLI.

It should provide three major outputs:
1. **Optimal predictions:** The predicted absolute ΔGs with uncertainties (and ΔΔGs between compounds with uncertainties) integrating all available experimental data in the network
2. **Reliability indicator for optimal predictions:** If there is more than one compound with experimental data, we also provide a leave-one-out assessment of how accurately we predicted each compound with experimental data by leaving its experimental free energy out of the DiffNet analysis and reporting the deviation statistics
3. **Retrospective debugging:** For compounds with experimental data, a comparison of directly computed edge ΔΔGs(without using any experimental data) with the experimental ΔΔGs, as well as how the absolute ΔGs (without experimental data corrections) correlate with experimental absolute ΔGs (shifting to the experimental mean in both cases)

For ligands in which we have expanded protonation states, we should collapse the absolute ΔGs for the microstates onto individual compounds, so the directly computed ΔΔGs in (3) would be omitted.

The perses CLI currently uses an SDF file for the ligands of interest. For now, we also presume that any retrospective ligands of interest are included in this SDF file as well. Because we may expand stereochemistry or protonation states prior to running calculations, we will need to include an SD tag for each ligand that specifies the parent ligand name. For lack of a better suggestion, we can call this `PARENT_LIGAND_ID` (suggestions welcomed), such that expanded microstates will have different titles in the SDF file but share the same `PARENT_LIGAND_ID`. If a molecule is not expanded, it will still have a `PARENT_LIGAND_ID`.

To integrate experimental data for these `PARENT_LIGAND_ID`s that are available, we will use a separate file. This could potentially be an SDF file, but it was suggested we may want to use the [same YAML format as protein-ligand benchmark](https://github.com/openforcefield/protein-ligand-benchmark/blob/main/data/cdk2/00_data/ligands.yml), though no detailed spec exists for this yet. We can always change this later, so I would suggest we include a CSV or YAML file with the following information:
```yaml
<id>:
  smiles: '[H][C]1=[N][C]2=[C]([O][C]([H])([H])[C]3([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]3([H])[H])[N]=[C]([N]([H])[C]3=[C]([H])[C]([H])=[C]([H])[C]([Br])=[C]3[H])[N]=[C]2[N]1[H]'
  measurement:
    type: IC50
    value: 6.8
    low_95ci: 2.3
    high_95ci: 9.1
    unit: micromolar
```
Feedback requested!
